services:
  database:
    build:
      context: .
      dockerfile: ./docker/database/DatabaseDockerfile
    ports: 
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: changeme
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
  api:
    depends_on:
      database:
        condition: service_started
    build:
      context: .
      dockerfile: ./docker/api/ApiDockerfile
    ports: 
      - "38001:38001"
    restart: unless-stopped
    environment:
      MEDIA_SHARE: /share
    volumes:
      - /share/fast:/share
      - ./database/db_config.json:/db_config.json
      - ./tomcat/conf/.keystore:/.keystore

  webui:
    image: tomcat
    ports:
      - "443:443"
    volumes:
      - ./tomcat/webapps:/usr/local/tomcat/webapps
      - ./tomcat/conf/server.xml:/usr/local/tomcat/conf/server.xml
      - ./tomcat/conf/.keystore:/root/.keystore

#volumes:
#  cifs_mount:
#    driver: local
#    driver_opts:
#      type: cifs
#      device: "//192.168.0.21/BMedia"
#      o: username=byron,password=Xtp9384Rgeq,iocharset=utf8
      