services:
  database:
    build:
      context: .
      dockerfile: ./docker/database/DatabaseDockerfile
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: changeme
  api:
    build:
      context: .
      dockerfile: ./docker/api/ApiDockerfile
    ports: 
      - "38001:38001"
# TODO: implement...seems difficult to dockerize nicely
#  ingester:
#    build:
#      context: .
#      dockerfile: ./docker/ingester/IngesterDockerfile
  webui:
    image: tomcat
    ports:
      - "8080:8080"
    volumes:
      - ./tomcat/webapps:/usr/local/tomcat/webapps